# Generated by Django 5.1.5 on 2026-02-22 00:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('civil_id', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debtors', to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_type', models.CharField(choices=[('cars', 'سيارات'), ('banks', 'بنوك'), ('real_estate', 'عقار'), ('cash', 'مبلغ مالي')], max_length=20)),
                ('deposit_or_sale_date', models.DateField()),
                ('proceed_amount', models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('machine_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{8}0$')])),
                ('distribution_date', models.DateField()),
                ('list_type', models.CharField(choices=[('temporary', 'مؤقتة'), ('final', 'نهائية')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='distributions.debtor')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{8}0$')])),
                ('creditor_name', models.CharField(max_length=100)),
                ('attachment_date', models.DateField()),
                ('attachment_type', models.CharField(max_length=80)),
                ('debt_amount', models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('debt_rank', models.PositiveSmallIntegerField(choices=[(1, 'ممتاز'), (2, 'رهن'), (3, 'نفقة'), (4, 'عمالي'), (5, 'حجز قبل البيع'), (6, 'حجز بعد البيع'), (7, 'عادي')])),
                ('distribution_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='distributions.distribution')),
            ],
            options={
                'ordering': ['debt_rank', 'attachment_date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['civil_id'], name='distributio_civil_i_0e42ac_idx'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['full_name'], name='distributio_full_na_d41919_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['machine_number'], name='distributio_machine_fc5b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['distribution_date'], name='distributio_distrib_576c42_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['department', 'list_type'], name='distributio_departm_8593ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='distribution',
            constraint=models.UniqueConstraint(fields=('department', 'machine_number'), name='uniq_machine_per_department'),
        ),
        migrations.AddIndex(
            model_name='creditor',
            index=models.Index(fields=['machine_number'], name='distributio_machine_2a2c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='creditor',
            index=models.Index(fields=['creditor_name'], name='distributio_credito_93c4a7_idx'),
        ),
    ]
