# Generated by Django 5.1.5 on 2026-02-22 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('distributions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('attendance_time', models.TimeField()),
                ('location', models.CharField(max_length=120)),
                ('floor', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='accounts.department')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='distributions.distribution')),
            ],
            options={
                'indexes': [models.Index(fields=['attendance_date'], name='reports_not_attenda_0a6805_idx'), models.Index(fields=['department'], name='reports_not_departm_55d0d9_idx')],
            },
        ),
    ]
